;<?php __halt_compiler() ?>
[Generel]
default=home
defaultLanguage=en
timezone="Europe/Berlin"
database=MySQL
mod_rewrite=true
cacheLifetime=86400
;databaseDir=
[MySQL]
mysql_host=localhost
mysql_port=3306
mysql_database=test
mysql_user=root
mysql_pass=
mysql_prefix=
[Session]
sessionName=sid
sessionCookieLifetime=14400
[Security]
secret="/(&FITV/&%F/&%DU&%V%I&RV/&%D/J%$($%$(/)(=)/&{]{]{[]{avI/&RTFJZ&FUJ/&ZGKu6kiu6rjuz6tjZ%FIU&TdhzfgkutudzTFI/%FI7z6tfu675iuzb7jRJ(/T/%ei8O(&REKI/Go7fujh65"
[Debugging]
displayErrors=true
logLevel=5